# Generated by Django 5.0.6 on 2024-05-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer_availablity',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
