# Generated by Django 5.0.6 on 2024-05-10 03:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_engineer_availablity_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Engineer_Availablity',
            new_name='Engineer_Availability',
        ),
    ]
